name: fa_flutter_core
description: Official FA Flutter core package.
version: 2.0.2
homepage: https://github.com/FieldAssist/fa_flutter_core.git

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^6.0.0

  # Preferences
  shared_preferences: ^2.5.3

  # FA dart core
  fa_dart_core:
    git:
      url: https://github.com/FieldAssist/fa_dart_core.git
      ref: feat/version_upgrade

  # Model Utilities
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Device Utilities
  in_app_update: ^4.2.3
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0

  webview_flutter: ^4.11.0
  flare_flutter: ^3.0.2
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  camera: ^0.11.1
#  collection: ^1.19.1
  dartx: ^1.2.0
  equatable: ^2.0.7
  expressions: ^0.2.5+2
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  #  flutter_geocoder: ^0.2.2-nullsafety
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  recase: ^4.1.0
  screenshot: ^3.0.0
  scrollable_positioned_list: ^0.3.8 #last updated 24 months ago
  sembast: ^3.8.5
  sembast_web: ^2.4.1
  shimmer: ^3.0.0
  sizer: ^3.0.5
  timelines: ^0.1.0 # last updated 4 yrs ago
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  provider: ^6.1.5
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Model Utilities
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
