name: fa_flutter_core
description: Official FA Flutter core package.
version: 2.0.2
homepage: https://github.com/FieldAssist/fa_flutter_core.git

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^5.4.1

  # Preferences
  shared_preferences: ^2.2.0

  # FA dart core
  fa_dart_core:
    git:
      url: https://github.com/FieldAssist/fa_dart_core.git
      ref: main

  # Model Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Device Utilities
  in_app_update: ^4.2.0
  device_info_plus: ^9.0.3
  device_information: ^0.0.4
  package_info_plus: ^4.1.0

  webview_flutter: ^4.2.3
  flare_flutter: ^3.0.2
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  camera: ^0.10.5+3
  collection: ^1.17.0
  dartx: ^1.2.0
  equatable: ^2.0.5
  expressions: ^0.2.5
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.7
  #  flutter_geocoder: ^0.2.2-nullsafety
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  get_it: ^7.6.0
  google_maps_flutter: ^2.4.0
  image_picker: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.6.0
  path_provider: ^2.1.0
  recase: ^4.1.0
  screenshot: ^2.1.0
  scrollable_positioned_list: ^0.3.8
  sembast: ^3.5.0+1
  sembast_web: ^2.1.3
  shimmer: ^3.0.0
  sizer: ^2.0.15
  timelines: ^0.1.0
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Model Utilities
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
